import {
  counterItems,
  expCards,
  socialImgs,
  techStackImgs,
  words,
} from "../constants";
import type { PortfolioData, Project } from "./portfolio-types";

const fallbackProjects: Project[] = [
  {
    id: "split-bill",
    title: "Split Bill Web App",
    description:
      "Split Bill is a web app that lets users upload a photo of a receipt and automatically splits the bill based on who ordered what. Assign items to each person, get an instant breakdown of costs, and share the payment info with friends. Simple, smart, and perfect for dining out together.",
    image: "/images/project6.png",
    link: "https://splitbill.rifqinaufal11.studio/",
    backgroundColor: "#e8f4f6",
    featured: true,
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "siap-undip-schedule",
    title: "Siap Undip Schedule",
    description: "",
    image: "/images/project3.png",
    link: "https://schedule.rifqinaufal11.studio/",
    backgroundColor: "#e8f4f6",
    featured: false,
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "employee-web",
    title: "EmployeeWeb - Visitor Management System",
    description: "",
    image: "/images/project1.png",
    link: "https://github.com/Rifqin-11/EmployeeWeb",
    backgroundColor: "#e4eefe",
    featured: false,
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "pln-calculator",
    title: "PLN Calculator",
    description: "",
    image: "/images/project2.png",
    link: "https://github.com/Rifqin-11/PLNCalculator",
    backgroundColor: "#F1EBFF",
    featured: false,
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "sitita",
    title: "Sitita Teknik Elektro",
    description: "",
    image: "/images/project4.png",
    link: "https://github.com/Rifqin-11/Sitita",
    backgroundColor: "#E6FFF7",
    featured: false,
    sortOrder: 5,
    isActive: true,
  },
];

export const fallbackPortfolioData: PortfolioData = {
  profile: {
    id: "main",
    heroName: "RIFQI NAUFAL",
    heroPrefix: "A CREATIVE",
    heroSubtitle:
      "Final year Electrical Engineering student with a passion for code.",
    profileImage: "/images/profile.png",
    location: "Semarang, Indonesia",
    email: "rifqinaufal9009@gmail.com",
    website: "rifqinaufal.tech",
    footerName: "RIFQI NAUFAL",
    brandName: "Rifqi Naufal",
    contactCta: "Let's work together",
  },
  heroRoles: words.slice(0, 4).map((word, index) => ({
    id: `role-${index + 1}`,
    text: word.text,
    imgPath: word.imgPath,
    sortOrder: index + 1,
    isActive: true,
  })),
  projects: fallbackProjects,
  experiences: expCards.map((card, index) => ({
    id: `experience-${index + 1}`,
    title: card.title,
    date: card.date,
    review: card.review,
    imgPath: card.imgPath,
    logoPath: card.logoPath,
    responsibilities: card.responsibilities,
    sortOrder: index + 1,
    isActive: true,
  })),
  skills: techStackImgs.map((skill, index) => ({
    id: `skill-${index + 1}`,
    name: skill.name,
    imgPath: skill.imgPath,
    sortOrder: index + 1,
    isActive: true,
  })),
  stats: counterItems.map((item, index) => ({
    id: `stat-${index + 1}`,
    label: item.label,
    value: item.value,
    suffix: item.suffix,
    sortOrder: index + 1,
    isActive: true,
  })),
  socialLinks: socialImgs.map((social, index) => ({
    id: `social-${index + 1}`,
    name: social.name,
    imgPath: social.imgPath,
    link: social.link,
    sortOrder: index + 1,
    isActive: true,
  })),
};
